CREATE DATABASE IF NOT EXISTS investment_portal;
USE investment_portal;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userid VARCHAR(40) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  zipcode VARCHAR(10) NOT NULL,
  role ENUM('Customer', 'Employee', 'Admin') NOT NULL DEFAULT 'Customer',
  wallet_address VARCHAR(80),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS investments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  usd_balance DECIMAL(12,2) NOT NULL DEFAULT 0,
  btc_balance DECIMAL(18,8) NOT NULL DEFAULT 0,
  eth_balance DECIMAL(18,8) NOT NULL DEFAULT 0,
  eur_balance DECIMAL(12,2) NOT NULL DEFAULT 0,
  risk_level ENUM('Low', 'Medium', 'High') NOT NULL DEFAULT 'Medium',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_investments_user FOREIGN KEY (user_id) REFERENCES users(id)
);

